In [1]:
'''Import Libraries. Note that cip_functions is a custom library of functions for this particular application.'''
import pandas as pd
from pandas import DataFrame, Series
import nltk.data
from nltk.corpus import stopwords
from nltk.corpus import wordnet as wn
from nltk.tokenize import TreebankWordTokenizer as tok
from openpyxl import load_workbook
from cip_functions import get_synset,sector_tagger,get_def,append_df_to_excel

In [2]:
'''Static Variables'''

english_stops = set(stopwords.words('english'))
french_stops = set(stopwords.words('french'))

In [25]:
df = pd.read_excel('CIP Concordance_Master.xlsx')
df['Total'] = df['Agri-Food'] + df['Natural Resources'] + df['CleanTech'] + df['Advanced Manuf'] + df['Digital'] + df['Health']
df['Category'] = df['Category'].map(lambda x: x.replace('/',' ').replace(',','').replace('(','').replace(')',''))
df.head(15)

,Category,CatCode,Agri-Food,Natural Resources,CleanTech,Advanced Manuf,Digital,Health,Total
0,Agricultural and domestic animal services,1.05,1,0,0,0,0,0,1
1,Agricultural and food products processing,1.04,1,0,0,0,0,0,1
2,Agricultural business and management,1.01,1,0,0,0,0,0,1
3,Agricultural mechanization,1.02,1,0,0,0,0,0,1
4,Agricultural production operations,1.03,1,0,0,0,0,0,1
5,Agricultural public services,1.08,1,0,0,0,0,0,1
6,Agriculture agriculture operations and related...,1.99,1,0,0,0,0,0,1
7,Agriculture general,1.00,1,0,0,0,0,0,1
8,Animal sciences,1.09,1,0,0,0,0,0,1
9,Applied horticulture horticultural business se...,1.06,1,0,0,0,0,0,1
10,Fishing and fisheries sciences and management,3.03,1,0,0,0,0,0,1
11,Food science and technology,1.10,1,0,0,0,0,0,1
12,Forestry,3.05,0,1,1,0,0,0,2
13,International agriculture,1.07,1,0,0,0,0,0,1
14,Natural resources and conservation other,3.99,0,1,1,0,0,0,2

In [26]:
agri = df.loc[df['Agri-Food']==1,['Category']]
digi = df.loc[df['Digital']==1,['Category']]
clean_tech = df.loc[df['CleanTech']==1,['Category']]
nat_res = df.loc[df['Natural Resources']==1,['Category']]
health = df.loc[df['Health']==1,['Category']]
manu = df.loc[df['Advanced Manuf']==1,['Category']]

In [34]:
agri_matrix = sector_tagger(agri['Category']).drop_duplicates()
agri_matrix.head(10)

,Categories,Synsets,Definition
0,agricultural,agricultural.a.01,relating to or used in or promoting agricultur...
1,domestic,domestic.n.01,a servant who is paid to perform menial tasks ...
2,animal,animal.n.01,a living organism characterized by voluntary m...
3,services,services.n.01,performance of duties or provision of space an...
5,food,food.n.01,any substance that can be metabolized by an an...
6,products,merchandise.n.01,commodities offered for sale
7,processing,processing.n.01,preparing or putting through a prescribed proc...
9,business,business.n.01,a commercial or industrial enterprise and the ...
10,management,management.n.01,the act of managing something
12,mechanization,mechanization.n.01,the condition of having a highly technical imp...

In [35]:
digi_matrix = sector_tagger(digi['Category']).drop_duplicates()
digi_matrix.head(10)

,Categories,Synsets,Definition
0,computer,computer.n.01,a machine for performing calculations automati...
1,engineering,technology.n.01,the practical application of science to commer...
4,technologies,technology.n.01,the practical application of science to commer...
5,technicians,technician.n.01,someone whose occupation involves training in ...
6,drafting,drafting.n.01,writing a first version to be filled out and p...
7,design,design.n.01,the act of working out the form of something (...
11,electrical,electrical.a.01,relating to or concerned with electricity
12,electronic,electronic.a.01,of or relating to electronics; concerned with ...
17,electronics,electronics.n.01,the branch of physics that deals with the emis...
18,communications,communications.n.01,the discipline that studies the principles of ...

In [36]:
clean_tech_matrix = sector_tagger(clean_tech['Category']).drop_duplicates()
clean_tech_matrix.head(10)

,Categories,Synsets,Definition
0,forestry,forestry.n.01,the science of planting and caring for forests...
1,natural,natural.n.01,someone regarded as certain to succeed
2,resources,resource.n.01,available source of wealth; a new or reserve s...
3,conservation,conservation.n.01,an occurrence of improvement by virtue of prev...
7,research,research.n.01,systematic investigation to establish facts
10,management,management.n.01,the act of managing something
11,policy,policy.n.01,a plan of action adopted by an individual or s...
12,plant,plant.n.01,buildings for carrying on industrial labor
13,sciences,science.n.01,a particular branch of scientific knowledge
14,soil,dirt.n.02,the state of being covered with unclean things

In [37]:
nat_res_matrix = sector_tagger(nat_res['Category']).drop_duplicates()
nat_res_matrix.head(10)

,Categories,Synsets,Definition
0,forestry,forestry.n.01,the science of planting and caring for forests...
1,natural,natural.n.01,someone regarded as certain to succeed
2,resources,resource.n.01,available source of wealth; a new or reserve s...
3,conservation,conservation.n.01,an occurrence of improvement by virtue of prev...
7,research,research.n.01,systematic investigation to establish facts
10,management,management.n.01,the act of managing something
11,policy,policy.n.01,a plan of action adopted by an individual or s...
12,plant,plant.n.01,buildings for carrying on industrial labor
13,sciences,science.n.01,a particular branch of scientific knowledge
14,soil,dirt.n.02,the state of being covered with unclean things

In [38]:
health_matrix = sector_tagger(health['Category']).drop_duplicates()
health_matrix.head(10)

,Categories,Synsets,Definition
0,biochemical,biochemical.a.01,of or relating to biochemistry; involving chem...
1,engineering,technology.n.01,the practical application of science to commer...
2,bioengineering,biotechnology.n.02,the branch of engineering science in which bio...
3,biomedical,biomedical.a.01,relating to the activities and applications of...
5,biological,biological.a.01,pertaining to biology or to life and living th...
6,biosystems,None,
8,computer,computer.n.01,a machine for performing calculations automati...
12,technologies,technology.n.01,the practical application of science to commer...
13,technicians,technician.n.01,someone whose occupation involves training in ...
14,electrical,electrical.a.01,relating to or concerned with electricity

In [39]:
manu_matrix = sector_tagger(manu['Category']).drop_duplicates()
manu_matrix.head(10)

,Categories,Synsets,Definition
0,aerospace,aerospace.n.01,the atmosphere and outer space considered as a...
1,aeronautical,aeronautical.a.01,of or pertaining to aeronautics
2,astronautical,astronautic.a.01,of or belonging to astronauts or the science o...
3,space,space.n.01,the unlimited expanse in which everything is l...
4,engineering,technology.n.01,the practical application of science to commer...
5,agricultural,agricultural.a.01,relating to or used in or promoting agricultur...
7,architectural,architectural.a.01,of or pertaining to the art and science of arc...
11,technology,technology.n.01,the practical application of science to commer...
12,technician,technician.n.01,someone whose occupation involves training in ...
13,architecture,architecture.n.01,an architectural product or work